### ISSUE TITLE
Error in ir.model.access.csv

### ISSUE THREAD

**Issue by diassynthesis** [akretion/logistics-center#1]
logistics-center / connector_logistics_center / security /ir.model.access.csv

change: model_connector_logistic_installed to model_connector_logistics_installed

**Comment by bealdav** [comment]
Hi, thanks to noticed me
I haven't change the model names, only module names, no time for this.
Feel free to do a pull request for all models with logistic instead of logistics
Thank you

**Comment by bealdav** [comment]
fixed
