### ISSUE TITLE
Example of the file: delivery_reply

### ISSUE THREAD

**Issue by awa-si** [akretion/logistics-center#3]
Hello,
trying full migration into 8.0
for some incoming jobs, just need some ideas.
Please, share example of the file delivery_reply.(txt|csv) to try imports.
Regards Andre

**Comment by bealdav** [comment]
Hi Andre, 

Thanks for your interest in these modules. 
I'm interested to collaborate for migrate logistics-center to v8.
If you speak french, there is an opportunity to exchange by phone, else here it's ok.

I will detail my vision here, I have not a lot of time today but i begin 
What is the plan:

In this issue: https://github.com/akretion/logistics-center/issues/4

Please, add your comments, thanks
